spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fyze
    username: fyze
    password: fyze
  liquibase:
    change-log: classpath:/db/changelog/test/data/db.changelog-test.yml
    drop-first: false # Setting this true will reset the data in local envt every time you boot the application
  web:
    cors:
      allowed-origin-patterns: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
  endpoint:
    env:
      show-values: ALWAYS
